// Blog/frontend/src/lib/components/Header.svelte
<script>
</script>

<header class="fixed w-full h-18 bg-gray-200">
	<div class="flex w-full justify-between p-4">
		<div class="bg-red-500 rounded-full w-10 h-10"></div>
		<div class="flex items-center gap-8">
			<span>Tags</span>
			<span>Archives</span>
			<span>Portfolio</span>
			<span>About</span>
			<button class="ring-1 rounded-full px-2">Login</button>
		</div>
	</div>
</header>

// portfolio/src/Components/Header.tsx
import '@/Styles/Header.css';

interface HeaderProps {
    sections: string[];
}

export default function Header({ sections }: HeaderProps){
    return (
        <header className="fixed flex justify-between w-full h-14 px-10 bg-darkboard items-center text-white drop-shadow-2xl z-20">
            <div className="w-10 h-10 rounded-full bg-yellow-chalk"/>
            <div className="h-full">
                <ul className="flex h-full">
                    {sections.map((section, index) => <li
                        className="relative section h-full w-20 mx-1 p-1 flex items-center justify-center"
                        key={index} 
                    >
                        <a href={`#${section}`}>
                            {section}
                        </a>
                    </li>)}
                </ul>
            </div>
        </header>
    );
}
